name: ai-chatbot
services:
  postgres:
    image: postgres:14
    container_name: ai-chatbot-postgres
    restart: always
    ports:
      - 5455:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: ai-chatbot